export type StreetWearCategory = 'tshirts' | 'hoodies' | 'shorts' | 'pants' | 'outerwear';

export interface StreetWearProduct {
  id: string;
  title: string;
  category: StreetWearCategory;
  image: string;
  baseCost: number;
  sizes: string[];
  features: string[];
}

export const VOLUME_TIERS = [
  { qty: 100, markup: 1.6, label: '100 pcs' },
  { qty: 250, markup: 1.5, label: '250 pcs' },
  { qty: 500, markup: 1.4, label: '500 pcs' },
] as const;

export type TierQty = (typeof VOLUME_TIERS)[number]['qty'];

export function getTierPrice(baseCost: number, tierQty: TierQty): number {
  const tier = VOLUME_TIERS.find((t) => t.qty === tierQty)!;
  return Math.ceil(baseCost * tier.markup * 100) / 100;
}

export function getAllTierPrices(baseCost: number) {
  return VOLUME_TIERS.map((tier) => ({
    qty: tier.qty,
    label: tier.label,
    unitPrice: Math.ceil(baseCost * tier.markup * 100) / 100,
  }));
}

export function getProductsByCategory(category: StreetWearCategory) {
  return STREETWEAR_PRODUCTS.filter((p) => p.category === category);
}

export const INITIAL_VISIBLE = 12;

export const CATEGORIES: {
  id: StreetWearCategory;
  name: string;
  description: string;
}[] = [
  { id: 'tshirts', name: 'T-Shirts', description: 'Heavyweight tees, boxy fits, vintage washes, and more' },
  { id: 'hoodies', name: 'Hoodies & Crewnecks', description: 'Pullover and zip-up hoodies, crewnecks, and tracksuits' },
  { id: 'shorts', name: 'Shorts', description: 'Sweat shorts, mesh shorts, cargo shorts, and athletic styles' },
  { id: 'pants', name: 'Pants & Joggers', description: 'Joggers, sweatpants, cargo pants, wide leg, and track pants' },
  { id: 'outerwear', name: 'Outerwear', description: 'Varsity jackets, bombers, windbreakers, and more' },
];

export const STREETWEAR_PRODUCTS: StreetWearProduct[] = [
  // ── T-Shirts ───────────────────────────────────────────────
  {
    id: 'heavyweight-tee-heavyweight-oversized',
    title: 'Heavyweight Tee — Heavyweight, Oversized',
    category: 'tshirts',
    image: 'tshirts/new-design-screen-printing-graphic-tshirts-men-custom-heavyw.webp',
    baseCost: 11.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Oversized', 'Boxy Fit', 'Cropped', 'Screen Print'],
  },
  {
    id: 'heavyweight-tee-oversized-boxy-fit',
    title: 'Heavyweight Tee — Oversized, Boxy Fit',
    category: 'tshirts',
    image: 'tshirts/unisex-oversized-fit-boxy-cropped-t-shirt-screen-printing-me.webp',
    baseCost: 12.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Oversized', 'Boxy Fit', 'Cropped', 'Raw Hem', 'Screen Print'],
  },
  {
    id: 'long-sleeve-tee-heavyweight-screen-printed',
    title: 'Long Sleeve Tee — Heavyweight, Screen Printed',
    category: 'tshirts',
    image: 'tshirts/custom-screen-printing-camo-graphic-tshirts-heavyweight-cott.webp',
    baseCost: 12.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Screen Print', 'Long Sleeve', 'Double Layer', 'Camo'],
  },
  {
    id: 'heavyweight-tee-heavyweight-oversized-2',
    title: 'Heavyweight Tee — Heavyweight, Oversized',
    category: 'tshirts',
    image: 'tshirts/asymmetrical-raw-hem-unisex-bozy-tshirts-custom-screen-print.webp',
    baseCost: 12.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Oversized', 'Raw Hem', 'Screen Print', '100% Cotton'],
  },
  {
    id: 'heavyweight-tee-heavyweight-acid-wash',
    title: 'Heavyweight Tee — Heavyweight, Acid Wash',
    category: 'tshirts',
    image: 'tshirts/manufacturer-custom-logo-230g-vintage-acid-washed-t-shirt-me.webp',
    baseCost: 12.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Acid Wash', 'Vintage Wash', 'Oversized', '100% Cotton'],
  },
  {
    id: 'heavyweight-tee-heavyweight-vintage-wash',
    title: 'Heavyweight Tee — Heavyweight, Vintage Wash',
    category: 'tshirts',
    image: 'tshirts/oversized-heavyweight-t-shirt-custom-screen-printed-men-vint.webp',
    baseCost: 13.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Oversized', 'Boxy Fit', 'Raw Hem'],
  },
  {
    id: 'heavyweight-tee-heavyweight-acid-wash-2',
    title: 'Heavyweight Tee — Heavyweight, Acid Wash',
    category: 'tshirts',
    image: 'tshirts/short-sleeve-100-cotton-heavyweight-tshirts-custom-screen-pr.webp',
    baseCost: 13.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Acid Wash', 'Sun Faded', 'Boxy Fit', 'Cropped'],
  },
  {
    id: 'heavyweight-tee-vintage-wash-sun-faded',
    title: 'Heavyweight Tee — Vintage Wash, Sun Faded',
    category: 'tshirts',
    image: 'tshirts/cotton-vintage-washed-unisex-oversized-t-shirt-short-sleeve.webp',
    baseCost: 13.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Oversized', 'Boxy Fit', 'Cropped'],
  },
  {
    id: 'heavyweight-tee-heavyweight-acid-wash-3',
    title: 'Heavyweight Tee — Heavyweight, Acid Wash',
    category: 'tshirts',
    image: 'tshirts/manufacturer-heavyweight-drop-shoulder-vintage-washed-oversi.webp',
    baseCost: 13.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Acid Wash', 'Vintage Wash', 'Oversized', '100% Cotton'],
  },
  {
    id: 'long-sleeve-tee-heavyweight-raw-hem',
    title: 'Long Sleeve Tee — Heavyweight, Raw Hem',
    category: 'tshirts',
    image: 'tshirts/double-layer-waffle-long-sleeve-tshirt-custom-applique-patch.webp',
    baseCost: 13.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Raw Hem', 'Embroidery', 'Long Sleeve', 'Double Layer'],
  },
  {
    id: 'long-sleeve-tee-heavyweight-vintage-wash',
    title: 'Long Sleeve Tee — Heavyweight, Vintage Wash',
    category: 'tshirts',
    image: 'tshirts/wholesale-heavyweight-100-cotton-screen-printing-tshirts-cus.webp',
    baseCost: 13.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Screen Print', '100% Cotton', 'Long Sleeve'],
  },
  {
    id: 'long-sleeve-tee-heavyweight-vintage-wash-2',
    title: 'Long Sleeve Tee — Heavyweight, Vintage Wash',
    category: 'tshirts',
    image: 'tshirts/oem-vintage-washed-streetwear-heavyweight-cotton-tshirts-men.webp',
    baseCost: 13.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Screen Print', 'Long Sleeve', 'Graphic'],
  },
  {
    id: 'long-sleeve-tee-heavyweight-screen-printed-2',
    title: 'Long Sleeve Tee — Heavyweight, Screen Printed',
    category: 'tshirts',
    image: 'tshirts/oem-manufacturer-custom-screen-print-graphic-tee-heavyweight.webp',
    baseCost: 13.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Screen Print', 'Long Sleeve', 'Double Layer', 'Graphic'],
  },
  {
    id: 'heavyweight-tee-vintage-wash-oversized',
    title: 'Heavyweight Tee — Vintage Wash, Oversized',
    category: 'tshirts',
    image: 'tshirts/hot-sale-unisex-oversized-fit-cotton-tshirts-custom-vintage.webp',
    baseCost: 13.8,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Oversized', 'Boxy Fit', 'Screen Print', 'Graphic'],
  },
  {
    id: 'heavyweight-tee-heavyweight-vintage-wash-2',
    title: 'Heavyweight Tee — Heavyweight, Vintage Wash',
    category: 'tshirts',
    image: 'tshirts/custom-screen-printing-heavyweight-cotton-t-shirt-men-short.webp',
    baseCost: 14.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Boxy Fit', 'Screen Print'],
  },
  {
    id: 'long-sleeve-tee-heavyweight-oversized',
    title: 'Long Sleeve Tee — Heavyweight, Oversized',
    category: 'tshirts',
    image: 'tshirts/custom-100-cotton-heavyweight-oversized-t-shirt-embroidery-l.webp',
    baseCost: 15.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Oversized', 'Boxy Fit', 'Raw Hem', 'Embroidery'],
  },
  {
    id: 'heavyweight-tee-vintage-wash-sun-faded-2',
    title: 'Heavyweight Tee — Vintage Wash, Sun Faded',
    category: 'tshirts',
    image: 'tshirts/thick-cotton-oversized-tshirts-custom-vintage-washed-men-scr.webp',
    baseCost: 17.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Oversized', 'Rhinestone', 'Screen Print'],
  },
  {
    id: 'long-sleeve-tee-heavyweight-vintage-wash-3',
    title: 'Long Sleeve Tee — Heavyweight, Vintage Wash',
    category: 'tshirts',
    image: 'tshirts/345gsm-heavyweight-retro-vintage-washed-tshirts-custom-scree.webp',
    baseCost: 22.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Oversized', 'Screen Print', 'Long Sleeve'],
  },
  {
    id: 'long-sleeve-tee-heavyweight-long-sleeve',
    title: 'Long Sleeve Tee — Heavyweight, Long Sleeve',
    category: 'tshirts',
    image: 'tshirts/new-trend-unisex-loose-fit-thick-cotton-tshirts-custom-graph.webp',
    baseCost: 16.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Long Sleeve', 'Double Layer', 'Graphic'],
  },
  {
    id: 'heavyweight-tee-heavyweight-oversized-3',
    title: 'Heavyweight Tee — Heavyweight, Oversized',
    category: 'tshirts',
    image: 'tshirts/high-street-oversized-fit-unisex-dtg-printed-graphic-tees-cu.webp',
    baseCost: 8.9,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Oversized', 'Graphic'],
  },
  {
    id: 'heavyweight-tee-heavyweight-acid-wash-4',
    title: 'Heavyweight Tee — Heavyweight, Acid Wash',
    category: 'tshirts',
    image: 'tshirts/heavyweight-color-acid-wash-sports-sleeveless-oversized-vest.jpg',
    baseCost: 10.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Acid Wash', 'Oversized'],
  },
  {
    id: 'heavyweight-tee-oversized-boxy-fit-2',
    title: 'Heavyweight Tee — Oversized, Boxy Fit',
    category: 'tshirts',
    image: 'tshirts/short-sleeve-comfort-colors-t-shirts-embroidery-logo-mens-ov.webp',
    baseCost: 18.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Oversized', 'Boxy Fit', 'Embroidery'],
  },
  {
    id: 'long-sleeve-tee-screen-printed-long-sleeve',
    title: 'Long Sleeve Tee — Screen Printed, Long Sleeve',
    category: 'tshirts',
    image: 'tshirts/streetwear-unisex-loose-fit-tshirts-custom-screen-printing-m.webp',
    baseCost: 21.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Screen Print', 'Long Sleeve', 'Double Layer'],
  },
  {
    id: 'heavyweight-tee-acid-wash-raw-hem',
    title: 'Heavyweight Tee — Acid Wash, Raw Hem',
    category: 'tshirts',
    image: 'tshirts/manufacturer-wholesale-high-quality-black-blank-acid-washed.webp',
    baseCost: 25.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Acid Wash', 'Raw Hem'],
  },
  {
    id: 'heavyweight-tee-embroidered',
    title: 'Heavyweight Tee — Embroidered',
    category: 'tshirts',
    image: 'tshirts/factory-wholesale-high-quality-basketball-jersey-custom-embr.jpg',
    baseCost: 26.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Embroidery'],
  },
  {
    id: 'heavyweight-tee',
    title: 'Heavyweight Tee',
    category: 'tshirts',
    image: 'tshirts/manufacturer-new-wash-water-to-do-old-european-and-american.jpg',
    baseCost: 7.6,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: [],
  },
  {
    id: 'heavyweight-tee-2',
    title: 'Heavyweight Tee',
    category: 'tshirts',
    image: 'tshirts/new-fashion-wash-water-to-do-old-european-and-american-hip-h.jpg',
    baseCost: 9.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: [],
  },
  // ── Hoodies & Crewnecks ────────────────────────────────────
  {
    id: 'pullover-hoodie-heavyweight-vintage-wash',
    title: 'Pullover Hoodie — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/hot-selling-basic-pullover-oversized-rhinestone-hoodie-men-c.webp',
    baseCost: 15.6,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Oversized', 'Rhinestone', 'Pullover'],
  },
  {
    id: 'pullover-hoodie-oversized-boxy-fit',
    title: 'Pullover Hoodie — Oversized, Boxy Fit',
    category: 'hoodies',
    image: 'hoodies/oem-manufacturer-custom-patchwork-embroidered-hoodie-men-box.webp',
    baseCost: 15.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Oversized', 'Boxy Fit', 'Cropped', 'Embroidery', 'Applique/Patch'],
  },
  {
    id: 'zip-up-hoodie-heavyweight-sun-faded',
    title: 'Zip Up Hoodie — Heavyweight, Sun Faded',
    category: 'hoodies',
    image: 'hoodies/applique-embroidery-patched-zip-up-hoodies-men-custom-sunfad.webp',
    baseCost: 16.3,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Sun Faded', 'Rhinestone', 'Embroidery', 'Zip Up'],
  },
  {
    id: 'zip-up-hoodie-heavyweight-rhinestone',
    title: 'Zip Up Hoodie — Heavyweight, Rhinestone',
    category: 'hoodies',
    image: 'hoodies/manufacturer-oem-custom-embroidery-logo-zip-up-hoodies-men-h.webp',
    baseCost: 16.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Rhinestone', 'Embroidery', 'Zip Up', 'French Terry'],
  },
  {
    id: 'pullover-hoodie-heavyweight-vintage-wash-2',
    title: 'Pullover Hoodie — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/oem-unisex-oversized-heavyweight-cotton-zip-hoodies-custom-s.webp',
    baseCost: 16.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Distressed', 'Oversized', 'Screen Print'],
  },
  {
    id: 'pullover-hoodie-heavyweight-oversized',
    title: 'Pullover Hoodie — Heavyweight, Oversized',
    category: 'hoodies',
    image: 'hoodies/creen-printing-logo-graphic-pullover-hoodies-heavyweight-cot.webp',
    baseCost: 16.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Oversized', 'Rhinestone', 'Pullover', 'Graphic'],
  },
  {
    id: 'zip-up-hoodie-oversized-rhinestone',
    title: 'Zip Up Hoodie — Oversized, Rhinestone',
    category: 'hoodies',
    image: 'hoodies/manufacturer-custom-allover-rhinestone-unisex-oversized-zip.webp',
    baseCost: 18.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Oversized', 'Rhinestone', 'Embroidery', 'Zip Up', 'Applique/Patch'],
  },
  {
    id: 'zip-up-hoodie-heavyweight-vintage-wash',
    title: 'Zip Up Hoodie — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/oversized-heavyweight-cotton-french-terry-hoodies-custom-emb.webp',
    baseCost: 18.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Oversized', 'Embroidery'],
  },
  {
    id: 'zip-up-hoodie-heavyweight-sun-faded-2',
    title: 'Zip Up Hoodie — Heavyweight, Sun Faded',
    category: 'hoodies',
    image: 'hoodies/100-cotton-heavyweight-hoodie-men-custom-applique-patched-ov.webp',
    baseCost: 18.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Sun Faded', 'Oversized', 'Zip Up', '100% Cotton'],
  },
  {
    id: 'zip-up-hoodie-heavyweight-vintage-wash-2',
    title: 'Zip Up Hoodie — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/new-vintage-washed-sunfaded-hoodies-oversized-fit-men-custom.webp',
    baseCost: 19.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Oversized', 'Embroidery'],
  },
  {
    id: 'pullover-hoodie-heavyweight-vintage-wash-3',
    title: 'Pullover Hoodie — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/custom-heavyweight-cotton-french-terry-oversized-pullover-me.webp',
    baseCost: 20.2,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Oversized', 'Pullover'],
  },
  {
    id: 'zip-up-hoodie-oversized-screen-printed',
    title: 'Zip Up Hoodie — Oversized, Screen Printed',
    category: 'hoodies',
    image: 'hoodies/custom-screen-printing-unisex-oversized-fit-graphic-hoodies.webp',
    baseCost: 20.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Oversized', 'Screen Print', 'Zip Up', 'French Terry', 'Graphic'],
  },
  {
    id: 'pullover-hoodie-heavyweight-vintage-wash-4',
    title: 'Pullover Hoodie — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/custom-logo-embroidery-patched-pullover-hoodie-oversized-fit.webp',
    baseCost: 20.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Oversized', 'Embroidery', 'Pullover'],
  },
  {
    id: 'pullover-hoodie-heavyweight-vintage-wash-5',
    title: 'Pullover Hoodie — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/factory-high-street-vintage-monkey-washed-sunfaded-hoodies-c.webp',
    baseCost: 20.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Pullover', 'French Terry'],
  },
  {
    id: 'zip-up-hoodie-heavyweight-sun-faded-3',
    title: 'Zip Up Hoodie — Heavyweight, Sun Faded',
    category: 'hoodies',
    image: 'hoodies/custom-heavyweight-cotton-streetwear-unisex-zipper-screen-pr.webp',
    baseCost: 21.3,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Sun Faded', 'Rhinestone', 'Screen Print', 'Zip Up'],
  },
  {
    id: 'zip-up-hoodie-heavyweight-vintage-wash-3',
    title: 'Zip Up Hoodie — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/factory-high-quality-custom-vintage-washed-zip-up-hoodie-men.webp',
    baseCost: 21.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Distressed', 'Oversized', 'Embroidery'],
  },
  {
    id: 'zip-up-hoodie-heavyweight-all-over-print',
    title: 'Zip Up Hoodie — Heavyweight, All-Over Print',
    category: 'hoodies',
    image: 'hoodies/100-cotton-heavyweight-hoodie-custom-allover-printed-zipper.webp',
    baseCost: 22.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'All-Over Print', 'Zip Up', '100% Cotton', 'Graphic'],
  },
  {
    id: 'zip-up-hoodie-heavyweight-sun-faded-4',
    title: 'Zip Up Hoodie — Heavyweight, Sun Faded',
    category: 'hoodies',
    image: 'hoodies/oversized-fit-unisex-heavyweight-zip-up-hoodie-custom-screen.webp',
    baseCost: 23.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Sun Faded', 'Distressed', 'Oversized', 'Screen Print'],
  },
  {
    id: 'pullover-hoodie-heavyweight-vintage-wash-6',
    title: 'Pullover Hoodie — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/unisex-oversized-heavyweight-hoodie-custom-embroidery-logo-m.webp',
    baseCost: 24.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Distressed', 'Oversized'],
  },
  {
    id: 'pullover-hoodie-vintage-wash-oversized',
    title: 'Pullover Hoodie — Vintage Wash, Oversized',
    category: 'hoodies',
    image: 'hoodies/custom-screen-printed-heavy-weight-hoodie-men-pullover-frenc.webp',
    baseCost: 25.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Oversized', 'Screen Print', 'Pullover', 'French Terry'],
  },
  {
    id: 'zip-up-hoodie-vintage-wash-sun-faded',
    title: 'Zip Up Hoodie — Vintage Wash, Sun Faded',
    category: 'hoodies',
    image: 'hoodies/450gsm-french-terry-thick-cotton-zip-up-hoodies-men-customs.webp',
    baseCost: 26.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Rhinestone', 'Zip Up', 'French Terry'],
  },
  {
    id: 'zip-up-hoodie-oversized-rhinestone-2',
    title: 'Zip Up Hoodie — Oversized, Rhinestone',
    category: 'hoodies',
    image: 'hoodies/oem-high-quality-retro-washed-zip-up-hoodies-custom-oversize.webp',
    baseCost: 27.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Oversized', 'Rhinestone', 'Embroidery', 'Zip Up', 'Applique/Patch'],
  },
  {
    id: 'tracksuit-set-heavyweight-sun-faded',
    title: 'Tracksuit Set — Heavyweight, Sun Faded',
    category: 'hoodies',
    image: 'hoodies/custom-embroidery-logo-patched-hoodies-sweatpants-sets-sunfa.webp',
    baseCost: 38.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Sun Faded', 'Puff Print', 'Embroidery', 'Applique/Patch'],
  },
  {
    id: 'zip-up-hoodie-embroidered-zip-up',
    title: 'Zip Up Hoodie — Embroidered, Zip Up',
    category: 'hoodies',
    image: 'hoodies/monsterboss-mens-100-cotton-french-terry-embroidered-full-fa.jpg',
    baseCost: 28.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Embroidery', 'Zip Up', 'French Terry', '100% Cotton'],
  },
  {
    id: 'tracksuit-set-heavyweight-vintage-wash',
    title: 'Tracksuit Set — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/heavyweight-vintage-washed-streetwear-sweatsuits-custom-logo.webp',
    baseCost: 32.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Embroidery', 'Applique/Patch'],
  },
  {
    id: 'tracksuit-set-vintage-wash-embroidered',
    title: 'Tracksuit Set — Vintage Wash, Embroidered',
    category: 'hoodies',
    image: 'hoodies/custom-streetwear-vintage-washed-unisex-thick-cotton-tracksu.webp',
    baseCost: 33.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Embroidery', 'Flared', 'Applique/Patch'],
  },
  {
    id: 'tracksuit-set-vintage-wash-sun-faded',
    title: 'Tracksuit Set — Vintage Wash, Sun Faded',
    category: 'hoodies',
    image: 'hoodies/two-piece-tracksuit-sweatsuits-custom-embroidery-logo-patche.webp',
    baseCost: 35.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Embroidery', 'Applique/Patch'],
  },
  {
    id: 'tracksuit-set-heavyweight-vintage-wash-2',
    title: 'Tracksuit Set — Heavyweight, Vintage Wash',
    category: 'hoodies',
    image: 'hoodies/high-street-vintage-washed-heavyweight-french-terry-tracksui.webp',
    baseCost: 39.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Embroidery', 'French Terry'],
  },
  {
    id: 'tracksuit-set-vintage-wash-sun-faded-2',
    title: 'Tracksuit Set — Vintage Wash, Sun Faded',
    category: 'hoodies',
    image: 'hoodies/vintage-sunfaded-wash-two-piece-tracksuits-sweatsuits-custom.webp',
    baseCost: 49.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Distressed', 'Rhinestone'],
  },
  // ── Shorts ─────────────────────────────────────────────────
  {
    id: 'sweat-shorts-heavyweight-acid-wash',
    title: 'Sweat Shorts — Heavyweight, Acid Wash',
    category: 'shorts',
    image: 'pants/customized-acid-wash-vintage-shorts-men-heavyweight-cotton-f.webp',
    baseCost: 13.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Acid Wash', 'Sun Faded', 'Rhinestone', 'French Terry'],
  },
  {
    id: 'cargo-shorts-oversized-rhinestone',
    title: 'Cargo Shorts — Oversized, Rhinestone',
    category: 'shorts',
    image: 'pants/factory-oem-100-cotton-cargo-shorts-men-custom-camo-printed.webp',
    baseCost: 13.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Oversized', 'Rhinestone', 'Wide Leg', 'Cargo', '100% Cotton'],
  },
  {
    id: 'sweat-shorts-acid-wash-sun-faded',
    title: 'Sweat Shorts — Acid Wash, Sun Faded',
    category: 'shorts',
    image: 'pants/custom-heavy-weight-cotton-shorts-pants-embroidery-acid-wash.webp',
    baseCost: 13.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Acid Wash', 'Sun Faded', 'Raw Hem', 'Embroidery', 'Fleece'],
  },
  {
    id: 'sweat-shorts-heavyweight-vintage-wash',
    title: 'Sweat Shorts — Heavyweight, Vintage Wash',
    category: 'shorts',
    image: 'pants/applique-logo-patched-shorts-custom-embroidery-heavyweight-c.webp',
    baseCost: 13.9,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Embroidery', 'Applique/Patch'],
  },
  {
    id: 'shorts-vintage-wash-sun-faded',
    title: 'Shorts — Vintage Wash, Sun Faded',
    category: 'shorts',
    image: 'pants/oem-french-terry-streetwear-sewat-shorts-custom-embroidery-l.webp',
    baseCost: 14.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Embroidery', 'French Terry', 'Applique/Patch'],
  },
  {
    id: 'sweat-shorts-heavyweight-sun-faded',
    title: 'Sweat Shorts — Heavyweight, Sun Faded',
    category: 'shorts',
    image: 'pants/heavyweight-cotton-side-logo-printed-shorts-custom-sunfaded.webp',
    baseCost: 14.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Sun Faded', 'Oversized', 'Raw Hem', 'Rhinestone'],
  },
  {
    id: 'basketball-shorts-vintage-wash-sun-faded',
    title: 'Basketball Shorts — Vintage Wash, Sun Faded',
    category: 'shorts',
    image: 'pants/custom-applique-embroidery-gym-fitness-basketball-shorts-men.webp',
    baseCost: 14.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Raw Hem', 'Embroidery', 'French Terry'],
  },
  {
    id: 'sweat-shorts-vintage-wash-raw-hem',
    title: 'Sweat Shorts — Vintage Wash, Raw Hem',
    category: 'shorts',
    image: 'pants/vintage-wash-thick-cotton-streetwear-sweat-shorts-custom-log.webp',
    baseCost: 14.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Raw Hem', 'Embroidery', 'French Terry', 'Applique/Patch'],
  },
  {
    id: 'cargo-shorts-vintage-wash-distressed',
    title: 'Cargo Shorts — Vintage Wash, Distressed',
    category: 'shorts',
    image: 'pants/custom-luxury-cargo-shorts-manufacturer-wholesale-men-workou.webp',
    baseCost: 14.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Distressed', 'Raw Hem', 'Cargo', 'Camo'],
  },
  {
    id: 'cargo-shorts-vintage-wash-sun-faded',
    title: 'Cargo Shorts — Vintage Wash, Sun Faded',
    category: 'shorts',
    image: 'pants/custom-luxury-sun-faded-cargo-shorts-5-inch-inseam-manufactu.webp',
    baseCost: 14.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Distressed', 'Cargo', 'Camo'],
  },
  {
    id: 'sweat-shorts-heavyweight-vintage-wash-2',
    title: 'Sweat Shorts — Heavyweight, Vintage Wash',
    category: 'shorts',
    image: 'pants/streetwear-heavyweight-cotton-shorts-custom-vintage-washed-s.webp',
    baseCost: 15.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Rhinestone', 'Embroidery'],
  },
  {
    id: 'shorts-heavyweight-acid-wash',
    title: 'Shorts — Heavyweight, Acid Wash',
    category: 'shorts',
    image: 'pants/custom-french-terry-gym-shorts-heavyweight-100-cotton-screen.webp',
    baseCost: 16.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Acid Wash', 'Vintage Wash', 'Sun Faded', 'Screen Print'],
  },
  {
    id: 'sweat-shorts-heavyweight-acid-wash-2',
    title: 'Sweat Shorts — Heavyweight, Acid Wash',
    category: 'shorts',
    image: 'pants/custom-drawstring-cotton-french-terry-distressed-embroidered.webp',
    baseCost: 16.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Acid Wash', 'Distressed', 'Oversized', 'Raw Hem'],
  },
  {
    id: 'sweat-shorts-sun-faded-distressed',
    title: 'Sweat Shorts — Sun Faded, Distressed',
    category: 'shorts',
    image: 'pants/custom-unisex-applique-logo-distressed-embroidery-shorts-pan.jpg',
    baseCost: 17.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Sun Faded', 'Distressed', 'Rhinestone', 'Embroidery', 'French Terry'],
  },
  {
    id: 'sweat-shorts-vintage-wash-sun-faded',
    title: 'Sweat Shorts — Vintage Wash, Sun Faded',
    category: 'shorts',
    image: 'pants/sunfaded-acid-vintage-washed-thick-cotton-shorts-men-custom.webp',
    baseCost: 17.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Raw Hem', 'Embroidery', 'Applique/Patch'],
  },
  {
    id: 'sweat-shorts-heavyweight-distressed',
    title: 'Sweat Shorts — Heavyweight, Distressed',
    category: 'shorts',
    image: 'pants/oem-heavyweight-cotton-french-terry-shorts-custom-striped-si.webp',
    baseCost: 18.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Distressed', 'Raw Hem', 'Wide Leg', 'French Terry'],
  },
  {
    id: 'sweat-shorts-vintage-wash-sun-faded-2',
    title: 'Sweat Shorts — Vintage Wash, Sun Faded',
    category: 'shorts',
    image: 'pants/manufacturer-oem-chenille-applique-embroidery-patched-shorts.webp',
    baseCost: 20.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Embroidery', '100% Cotton', 'Applique/Patch'],
  },
  {
    id: 'sweat-shorts-heavyweight-vintage-wash-4',
    title: 'Sweat Shorts — Heavyweight, Vintage Wash',
    category: 'shorts',
    image: 'hoodies/heavyweight-cotton-hoodies-sweat-shorts-set-custom-vintage-w.webp',
    baseCost: 28.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Embroidery', 'Applique/Patch'],
  },
  {
    id: 'sweat-shorts-heavyweight-embroidered',
    title: 'Sweat Shorts — Heavyweight, Embroidered',
    category: 'shorts',
    image: 'hoodies/custom-logo-print-applique-patched-embroidery-shorts-tracksu.webp',
    baseCost: 29.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Embroidery', 'Applique/Patch'],
  },
  {
    id: 'sweat-shorts-vintage-wash-fleece',
    title: 'Sweat Shorts — Vintage Wash, Fleece',
    category: 'shorts',
    image: 'hoodies/fleece-vintage-washed-hoodies-sweatpants-sets-men-custom-log.webp',
    baseCost: 7.5,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Fleece'],
  },
  {
    id: 'shorts-heavyweight-oversized',
    title: 'Shorts — Heavyweight, Oversized',
    category: 'shorts',
    image: 'tshirts/vintage-heavyweight-t-shirt-high-street-oversized-short-slee.jpg',
    baseCost: 12.8,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Oversized'],
  },
  {
    id: 'shorts-puff-print-french-terry',
    title: 'Shorts — Puff Print, French Terry',
    category: 'shorts',
    image: 'pants/french-terry-drawstring-custom-men-puff-print-shorts.jpg',
    baseCost: 19.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Puff Print', 'French Terry'],
  },
  {
    id: 'shorts-vintage-wash-embroidered',
    title: 'Shorts — Vintage Wash, Embroidered',
    category: 'shorts',
    image: 'hoodies/factory-oem-mens-streetwear-shorts-tracksuits-set-custom-vin.webp',
    baseCost: 32.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Embroidery'],
  },
  {
    id: 'sweat-shorts-embroidered-appliqu',
    title: 'Sweat Shorts — Embroidered, Appliqué',
    category: 'shorts',
    image: 'hoodies/new-trend-custom-logo-embroidery-patched-two-piece-sets-swea.webp',
    baseCost: 35.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Embroidery', 'Applique/Patch'],
  },
  {
    id: 'shorts-oversized',
    title: 'Shorts — Oversized',
    category: 'shorts',
    image: 'tshirts/solid-color-pure-cotton-mens-short-sleeved-blank-shirt-overs.jpg',
    baseCost: 10.8,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    features: ['Oversized'],
  },
  {
    id: 'shorts-100-cotton',
    title: 'Shorts — 100% Cotton',
    category: 'shorts',
    image: 'tshirts/210g-high-quality-100-cotton-drop-shoulder-t-shirt-solid-col.jpg',
    baseCost: 11.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['100% Cotton'],
  },
  {
    id: 'shorts',
    title: 'Shorts',
    category: 'shorts',
    image: 'hoodies/manufacturer-american-fashion-brand-heavy-washed-waste-soil.jpg',
    baseCost: 23.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: [],
  },
  {
    id: 'sweat-shorts',
    title: 'Sweat Shorts',
    category: 'shorts',
    image: 'hoodies/high-quality-streetwear-two-piece-hoodie-shorts-sets-custom.webp',
    baseCost: 25.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: [],
  },
  // ── Pants & Joggers ────────────────────────────────────────
  {
    id: 'sweatpants-sun-faded-oversized',
    title: 'Sweatpants — Sun Faded, Oversized',
    category: 'pants',
    image: 'pants/oem-oversized-straight-wide-leg-sweatpants-men-custom-sun-fa.webp',
    baseCost: 15.3,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Sun Faded', 'Oversized', 'Rhinestone', 'Wide Leg', 'Flared'],
  },
  {
    id: 'sweatpants-acid-wash-vintage-wash',
    title: 'Sweatpants — Acid Wash, Vintage Wash',
    category: 'pants',
    image: 'pants/100-cotton-unisex-oversized-fit-wide-leg-sweat-pants-custom.webp',
    baseCost: 15.6,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Acid Wash', 'Vintage Wash', 'Oversized', 'Raw Hem', 'Wide Leg'],
  },
  {
    id: 'sweatpants-heavyweight-acid-wash',
    title: 'Sweatpants — Heavyweight, Acid Wash',
    category: 'pants',
    image: 'pants/heavyweight-cotton-vintage-sweat-pants-custom-printing-men-a.webp',
    baseCost: 15.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Acid Wash', 'Vintage Wash', 'Distressed', 'Oversized'],
  },
  {
    id: 'sweatpants-vintage-wash-sun-faded',
    title: 'Sweatpants — Vintage Wash, Sun Faded',
    category: 'pants',
    image: 'pants/oem-vintage-washed-stripe-sweat-pants-custom-100-cotton-sun.webp',
    baseCost: 16.3,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Embroidery', 'Flared', '100% Cotton'],
  },
  {
    id: 'sweatpants-heavyweight-oversized',
    title: 'Sweatpants — Heavyweight, Oversized',
    category: 'pants',
    image: 'pants/oem-heavyweight-100-cotton-oversized-wide-leg-sweat-track-pa.webp',
    baseCost: 16.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Oversized', 'Embroidery', 'Wide Leg', '100% Cotton'],
  },
  {
    id: 'joggers-vintage-wash-raw-hem',
    title: 'Joggers — Vintage Wash, Raw Hem',
    category: 'pants',
    image: 'pants/factory-custom-embroidery-logo-patched-applique-flared-jogge.webp',
    baseCost: 16.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Raw Hem', 'Embroidery', 'Flared', 'Applique/Patch'],
  },
  {
    id: 'sweatpants-heavyweight-oversized-2',
    title: 'Sweatpants — Heavyweight, Oversized',
    category: 'pants',
    image: 'pants/manufacturer-oem-100-cotton-heavyweight-wide-leg-sweatpants.webp',
    baseCost: 16.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Oversized', 'Wide Leg', '100% Cotton', 'Camo'],
  },
  {
    id: 'sweatpants-heavyweight-vintage-wash-2',
    title: 'Sweatpants — Heavyweight, Vintage Wash',
    category: 'pants',
    image: 'pants/factory-custom-distressed-vintage-washed-thick-cotton-track.webp',
    baseCost: 17.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Distressed', 'Oversized', 'Wide Leg'],
  },
  {
    id: 'joggers-heavyweight-vintage-wash',
    title: 'Joggers — Heavyweight, Vintage Wash',
    category: 'pants',
    image: 'pants/distressed-vintage-washed-track-jogger-pants-custom-rhinesto.webp',
    baseCost: 17.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Distressed', 'Rhinestone', 'Wide Leg'],
  },
  {
    id: 'sweatpants-heavyweight-oversized-3',
    title: 'Sweatpants — Heavyweight, Oversized',
    category: 'pants',
    image: 'pants/heavyweight-cotton-screen-printing-wide-leg-track-pants-men.webp',
    baseCost: 17.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Oversized', 'Embroidery', 'Screen Print', 'Wide Leg'],
  },
  {
    id: 'cargo-pants-heavyweight-vintage-wash',
    title: 'Cargo Pants — Heavyweight, Vintage Wash',
    category: 'pants',
    image: 'pants/vintage-washed-heavyweight-cotton-pants-trousers-men-oversiz.webp',
    baseCost: 17.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Oversized', 'Wide Leg', 'Cargo'],
  },
  {
    id: 'sweatpants-heavyweight-vintage-wash-3',
    title: 'Sweatpants — Heavyweight, Vintage Wash',
    category: 'pants',
    image: 'pants/factory-customized-100-cotton-heavyweight-sweatpants-men-vin.webp',
    baseCost: 17.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Wide Leg', '100% Cotton'],
  },
  {
    id: 'sweatpants-heavyweight-vintage-wash-4',
    title: 'Sweatpants — Heavyweight, Vintage Wash',
    category: 'pants',
    image: 'pants/new-trend-heavyweight-cotton-oversized-track-pants-men-custo.webp',
    baseCost: 18.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Oversized', 'Wide Leg'],
  },
  {
    id: 'sweatpants-heavyweight-oversized-4',
    title: 'Sweatpants — Heavyweight, Oversized',
    category: 'pants',
    image: 'pants/oem-heavyweight-100-cotton-oversized-wide-leg-sweat-track-pa.webp',
    baseCost: 18.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Oversized', 'Embroidery', 'Wide Leg', '100% Cotton'],
  },
  {
    id: 'sweatpants-heavyweight-sun-faded',
    title: 'Sweatpants — Heavyweight, Sun Faded',
    category: 'pants',
    image: 'pants/heavyweight-cotton-streetwear-track-pants-men-custom-sunfade.webp',
    baseCost: 18.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Sun Faded', 'Embroidery', 'Flared', 'Applique/Patch'],
  },
  {
    id: 'track-pants-heavyweight-vintage-wash',
    title: 'Track Pants — Heavyweight, Vintage Wash',
    category: 'pants',
    image: 'pants/manufacturer-oem-heavyweight-cotton-side-rhinestone-track-pa.webp',
    baseCost: 19.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Rhinestone', 'Wide Leg'],
  },
  {
    id: 'sweatpants-heavyweight-vintage-wash-5',
    title: 'Sweatpants — Heavyweight, Vintage Wash',
    category: 'pants',
    image: 'pants/heavyweight-cotton-vintage-sunfaded-washed-sweat-pants-custo.webp',
    baseCost: 20.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Puff Print', 'Rhinestone'],
  },
  {
    id: 'sweatpants-vintage-wash-sun-faded-2',
    title: 'Sweatpants — Vintage Wash, Sun Faded',
    category: 'pants',
    image: 'pants/screen-printed-logo-heavy-cotton-wide-leg-sweatpants-custom.webp',
    baseCost: 21.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Raw Hem', 'Screen Print', 'Wide Leg'],
  },
  {
    id: 'sweatpants-heavyweight-vintage-wash-6',
    title: 'Sweatpants — Heavyweight, Vintage Wash',
    category: 'pants',
    image: 'pants/unisex-streetwear-heavyweight-cotton-sweat-pants-men-custom.webp',
    baseCost: 22.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Rhinestone', 'Flared'],
  },
  {
    id: 'sweatpants-vintage-wash-sun-faded-3',
    title: 'Sweatpants — Vintage Wash, Sun Faded',
    category: 'pants',
    image: 'pants/vintage-washed-thick-cotton-french-terry-sweat-pants-mens-cu.webp',
    baseCost: 23.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Vintage Wash', 'Sun Faded', 'Rhinestone', 'Wide Leg', 'French Terry'],
  },
  {
    id: 'sweatpants-acid-wash-vintage-wash-2',
    title: 'Sweatpants — Acid Wash, Vintage Wash',
    category: 'pants',
    image: 'pants/custom-embroidery-logo-heavy-weight-stacked-flare-sweat-pant.webp',
    baseCost: 24.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Acid Wash', 'Vintage Wash', 'Embroidery', 'Flared', 'Fleece'],
  },
  {
    id: 'sweatpants-heavyweight-acid-wash-2',
    title: 'Sweatpants — Heavyweight, Acid Wash',
    category: 'pants',
    image: 'pants/vintage-acid-wash-heavyweight-cotton-sweatpants-men-custom-e.webp',
    baseCost: 25.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Acid Wash', 'Vintage Wash', 'Rhinestone', 'Embroidery'],
  },
  {
    id: 'sweatpants-acid-wash-sun-faded',
    title: 'Sweatpants — Acid Wash, Sun Faded',
    category: 'pants',
    image: 'pants/custom-embroidery-french-terry-straight-leg-track-sweat-pant.webp',
    baseCost: 26.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Acid Wash', 'Sun Faded', 'Rhinestone', 'Embroidery', 'French Terry'],
  },
  {
    id: 'joggers-heavyweight-distressed',
    title: 'Joggers — Heavyweight, Distressed',
    category: 'pants',
    image: 'pants/distressed-washed-embroidery-logo-track-jogger-pants-mens-he.webp',
    baseCost: 28.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Distressed', 'Rhinestone', 'Embroidery', 'Wide Leg'],
  },
  {
    id: 'sweatpants-heavyweight-vintage-wash-7',
    title: 'Sweatpants — Heavyweight, Vintage Wash',
    category: 'pants',
    image: 'pants/heavyweight-100-cotton-straight-leg-sweatpants-men-custom-lo.webp',
    baseCost: 32.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Sun Faded', 'Flared', '100% Cotton'],
  },
  {
    id: 'cargo-pants-zip-up-flared',
    title: 'Cargo Pants — Zip Up, Flared',
    category: 'pants',
    image: 'pants/straight-leg-pockets-cargo-pants-decorate-zipper-rivet-slim.webp',
    baseCost: 29.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Zip Up', 'Flared', 'Cargo'],
  },
  {
    id: 'cargo-pants-cargo-denim',
    title: 'Cargo Pants — Cargo, Denim',
    category: 'pants',
    image: 'pants/high-quality-mens-pants-straight-leg-slim-fit-stacked-jeans.webp',
    baseCost: 27.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Cargo'],
  },
  {
    id: 'sweatpants-wide-leg-spliced',
    title: 'Sweatpants — Wide Leg, Spliced',
    category: 'pants',
    image: 'pants/spliced-double-waist-wide-leg-pants-sports-sweatpants-men.jpg',
    baseCost: 10.8,
    sizes: ['S', 'M', 'L', 'XL'],
    features: [],
  },
  // ── Outerwear ──────────────────────────────────────────────
  {
    id: 'jacket-heavyweight-vintage-wash',
    title: 'Jacket — Heavyweight, Vintage Wash',
    category: 'outerwear',
    image: 'hoodies/low-moq-high-street-unisex-oversized-heavyweight-cotton-hood.webp',
    baseCost: 22.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Vintage Wash', 'Oversized', 'Zip Up'],
  },
  {
    id: 'varsity-jacket-boxy-fit-cropped',
    title: 'Varsity Jacket — Boxy Fit, Cropped',
    category: 'outerwear',
    image: 'tshirts/high-quality-embroidery-baseball-bomber-jacket-full-zipper-v.webp',
    baseCost: 35.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Boxy Fit', 'Cropped', 'Embroidery', 'Zip Up'],
  },
  {
    id: 'jacket-boxy-fit-embroidered',
    title: 'Jacket — Boxy Fit, Embroidered',
    category: 'outerwear',
    image: 'tshirts/chenille-embroidery-appliques-jacket-men-boxy-twill-jersey-h.webp',
    baseCost: 26.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Boxy Fit', 'Embroidery', 'Applique/Patch'],
  },
  {
    id: 'jacket-embroidered-long-sleeve',
    title: 'Jacket — Embroidered, Long Sleeve',
    category: 'outerwear',
    image: 'tshirts/factory-directly-custom-basketball-team-chenille-patched-emb.webp',
    baseCost: 26.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Embroidery', 'Long Sleeve', 'Applique/Patch'],
  },
  {
    id: 'bomber-jacket-boxy-fit-embroidered',
    title: 'Bomber Jacket — Boxy Fit, Embroidered',
    category: 'outerwear',
    image: 'tshirts/mens-jacket-racing-style-custom-patchwork-letter-embroidery.webp',
    baseCost: 35.6,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Boxy Fit', 'Embroidery', 'Applique/Patch'],
  },
  {
    id: 'bomber-jacket-boxy-fit-zip-up',
    title: 'Bomber Jacket — Boxy Fit, Zip Up',
    category: 'outerwear',
    image: 'tshirts/high-quality-custom-boucle-pu-patchwork-bomber-racing-jacket.webp',
    baseCost: 35.6,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Boxy Fit', 'Zip Up', 'Applique/Patch'],
  },
  {
    id: 'jacket-boxy-fit-cropped',
    title: 'Jacket — Boxy Fit, Cropped',
    category: 'outerwear',
    image: 'tshirts/single-breasted-college-track-jacket-baseball-letterman-boxy.webp',
    baseCost: 35.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Boxy Fit', 'Cropped', 'Embroidery'],
  },
  {
    id: 'windbreaker-embroidered-appliqu',
    title: 'Windbreaker — Embroidered, Appliqué',
    category: 'outerwear',
    image: 'tshirts/factory-custom-applique-embroidery-fashion-camouflage-mens-w.jpg',
    baseCost: 36.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Embroidery', 'Camo', 'Applique/Patch'],
  },
  {
    id: 'varsity-jacket-embroidered-fleece',
    title: 'Varsity Jacket — Embroidered, Fleece',
    category: 'outerwear',
    image: 'tshirts/thickened-lining-winter-warm-baseball-jacket-leather-sleeve.webp',
    baseCost: 36.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Embroidery', 'Fleece', 'Applique/Patch'],
  },
  {
    id: 'windbreaker-track-pants-embroidered',
    title: 'Windbreaker Track Pants — Embroidered',
    category: 'pants',
    image: 'pants/windbreaker-track-pants-custom-embroidery-logo-men-side-butt.webp',
    baseCost: 16.8,
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    features: ['Embroidery', 'Wide Leg'],
  },
  {
    id: 'windbreaker-track-pants-screen-printed',
    title: 'Windbreaker Track Pants — Screen Printed',
    category: 'pants',
    image: 'pants/screen-printing-logo-sportswear-windbreaker-pants-custom-ela.webp',
    baseCost: 16.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Screen Print', 'Wide Leg'],
  },
  {
    id: 'jacket-heavyweight-zip-up',
    title: 'Jacket — Heavyweight, Zip Up',
    category: 'outerwear',
    image: 'hoodies/heavyweight-wool-winter-zipper-hooded-jacket.jpg',
    baseCost: 18.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Heavyweight', 'Zip Up'],
  },
  {
    id: 'windbreaker-zip-up-appliqu',
    title: 'Windbreaker — Zip Up, Appliqué',
    category: 'outerwear',
    image: 'tshirts/customized-logo-nylon-wool-color-block-patchwork-jacket-mens.webp',
    baseCost: 27.6,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Zip Up', 'Applique/Patch'],
  },
  {
    id: 'puffer-jacket-puff-print-zip-up',
    title: 'Puffer Jacket — Puff Print, Zip Up',
    category: 'outerwear',
    image: 'tshirts/mens-winter-casual-fashion-down-coat-huili-wholesale-custom.webp',
    baseCost: 29.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Puff Print', 'Zip Up'],
  },
  {
    id: 'varsity-jacket-embroidered-appliqu',
    title: 'Varsity Jacket — Embroidered, Appliqué',
    category: 'outerwear',
    image: 'tshirts/custom-chenille-applique-embroidery-varsity-jacket-y2k-vinta.webp',
    baseCost: 29.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Embroidery', 'Applique/Patch'],
  },
  {
    id: 'varsity-jacket-embroidered-appliqu-2',
    title: 'Varsity Jacket — Embroidered, Appliqué',
    category: 'outerwear',
    image: 'tshirts/woolen-leather-sleeve-appliques-patchwork-varsity-mens-jacke.webp',
    baseCost: 32.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Embroidery', 'Applique/Patch'],
  },
  {
    id: 'puffer-jacket-puff-print-zip-up-2',
    title: 'Puffer Jacket — Puff Print, Zip Up',
    category: 'outerwear',
    image: 'tshirts/high-quality-mens-stand-collar-removable-hood-windproof-past.webp',
    baseCost: 39.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Puff Print', 'Zip Up'],
  },
  {
    id: 'jacket-zip-up',
    title: 'Jacket — Zip Up',
    category: 'outerwear',
    image: 'hoodies/mens-clothing-manufacturer-zip-up-hoodie-jacket-men-custom-s.webp',
    baseCost: 23.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Zip Up'],
  },
  {
    id: 'windbreaker-pullover-color-block',
    title: 'Windbreaker — Pullover, Color Block',
    category: 'outerwear',
    image: 'tshirts/streetbutterfly-men-s-half-zip-colorblock-windbreaker-pullov.jpg',
    baseCost: 25.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Pullover'],
  },
  {
    id: 'jacket-embroidered',
    title: 'Jacket — Embroidered',
    category: 'outerwear',
    image: 'tshirts/blank-jackets-custom-embroidery.jpg',
    baseCost: 28.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: ['Embroidery'],
  },
  {
    id: 'windbreaker-color-block-windbreaker',
    title: 'Windbreaker — Color Block',
    category: 'outerwear',
    image: 'tshirts/high-quality-summer-nylon-mens-jacket-custom-soft-shell-jack.webp',
    baseCost: 24.8,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: [],
  },
  {
    id: 'windbreaker-windbreaker-2',
    title: 'Windbreaker Set — Two-Piece',
    category: 'outerwear',
    image: 'pants/custom-winter-two-piece-jacket-pants-streetwear-mens-windbre.webp',
    baseCost: 33.5,
    sizes: ['M', 'L', 'XL', '2XL'],
    features: [],
  },
];
